### ISSUE TITLE
Please update offset

### ISSUE THREAD

**Issue by 330938192** [boowampp/ApexDmaCheatUpdated#3]
Please update offset, the game has been updated, by the way ask if you can add no kmbox mode

**Comment by boowampp** [comment]
il update offsets soon but why do you own a dma card and not have a kmbox ?

**Comment by 330938192** [comment]
emmm, I forgot to buy it

**Comment by boowampp** [comment]
i would buy one 90% of cheats use kmbox

**Comment by 330938192** [comment]
I would consider buying it because I thought aimbot was easy to detect and dma only read memory perspective would be more secure？

**Comment by boowampp** [comment]
yeah kmbox does not write memory like non kmbox aimbot
