### ISSUE TITLE
No visuals drawn

### ISSUE THREAD

**Issue by yasin-zk** [boowampp/ApexDmaCheatUpdated#4]
Hi, the esp is not working. Nothing is rendered on second pc.

Are the offsets for steam or origin platform?

![image](https://github.com/boowampp/ApexDmaCheatUpdated/assets/82512972/4bc1491a-a096-4f28-b29f-1c9505679426)

**Comment by boowampp** [comment]
i will update it when i have time

**Comment by Spookyisnice** [comment]
did you update ?

**Comment by yasin-zk** [comment]
> did you update ?

You can use this repo, look at glow.hpp and apply W2S + Rendering on the transparent screen :) 


To get the newest offsets dump with scylla, and upload the dump to this [link](https://casualhacks.net/apexdream/apexdumper.html)
